version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  exam-solver-nougat:
    build:
      context: ./exam-solver-nougat/.
      dockerfile: Dockerfile
    image: exam-solver-nougat:latest
    container_name: exam_solver_nougat
    restart: unless-stopped
    ports:
      - "8503:8503"
    environment:
      NO_GPU: "1"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
