spring:
  application:
    name: exam-solver-preprocessor

server:
  port: 8082

preprocessor:
  exercise-delimiters:
    es: "=== EJERCICIO ==="
    en: "=== EXERCISE ==="
    de: "=== AUFGABE ==="
    fr: "=== EXERCICE ==="
